### ISSUE TITLE
511 on the Twitter Updates section

### ISSUE THREAD

**Issue by arena** [COLLIER72/COLLIER72#1]
...maybe it should just say 511 instead of 511.org?

![image](https://cloud.githubusercontent.com/assets/411070/7600076/f2444cb8-f8bc-11e4-8e85-e2bc248d7c48.png)

**Comment by COLLIER72** [comment]
Yes.

Sent from my iPhone

On May 12, 2015, at 6:39 PM, Arena <notifications@github.com<mailto:notifications@github.com>> wrote:

...maybe it should just say 511 instead of 511.orghttp://511.org?

[https://cloud.githubusercontent.com/assets/411070/7600076/f2444cb8-f8bc-11e4-8e85-e2bc248d7c48.png]https://cloud.githubusercontent.com/assets/411070/7600076/f2444cb8-f8bc-11e4-8e85-e2bc248d7c48.png

**Comment by arena** [comment]
Changed.
