### ISSUE TITLE
Change pictures

### ISSUE THREAD

**Issue by COLLIER72** [COLLIER72/COLLIER72#8]
Get connected page does not allow for image change.

Main page does not allow for image change at the bottom three images.

Make a plan page does not allow for image change on the last image.

**Comment by arena** [comment]
We need to change these by substituting image files. If you have the images please share a dropbox folder or email them to me and I will optimize and replace accordingly.

**Comment by COLLIER72** [comment]
I will send you a location when I have them ready.

**Comment by arena** [comment]
ok. it's an easy change. 

In case you get inspired to do it yourself or want to reference this issue in the future if a new image comes in that you want to use..

The images are located in the directory:
app/assets/images/static

The tricky thing is that there are multiple sizes per image so that it works with the responsive framework.

**Comment by arena** [comment]
in case it's helpful this is a good guide to free-to-use imagery
https://medium.com/@dustin/stock-photos-that-dont-suck-62ae4bcbe01b

**Comment by arena** [comment]
I set up a sketch file that can be used to export the required sizes. I'll check in the Sketch file in case it helps somebody change these. Ideally, they will become part of the CMS in future iterations. ...but, for now, the template is there. 

..and just because it's so easy I'm going to change the images to some abstract beachy, flowery things.

**Comment by arena** [comment]
this is what I have locally:
![image](https://cloud.githubusercontent.com/assets/411070/7778799/bf434e08-0083-11e5-8523-0676a4041810.png)

maybe those work?

**Comment by arena** [comment]
I didn't find a easy image for the 'make a plan' pg right away. ..I agree that the one there doesn't feel very Florida. :) 

Will wait for imagery and then also check in the source file for future use in case it helps.

**Comment by arena** [comment]
There are also some pretty great images available via the Creative Commons Attribution License on Flickr, like this squirrel from Naples, FL https://www.flickr.com/photos/132033298@N04/17618223101/in/pool-naplesflorida

in case you want to browse:
https://www.flickr.com/search/?license=1%2C2%2C9%2C10&text=naples%2C%20fl&advanced=1

**Comment by arena** [comment]
Pushing new images to heroku right now. Please reload the site and let me know what you think. Some images need to be attributed on the about page (see google doc for details).

**Comment by arena** [comment]
I still need to check the cropping of mobile versions, but I think most images that needed to be replaced are good. At least, good for now. It would be great to have a photographer spend some time improving on the imagery.

**Comment by arena** [comment]
Closing this issue. Status: Good for launch, with inspiring imagery for a local photographer to riff off of.
